# name: GitHub Actions Demo
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "üçè This job's status is ${{ job.status }}."

name: AWS CDK Synth

on: [push]

jobs:
  aws-cdk-synth:
    runs-on: ubuntu-latest
    environment: Development

    # Permissions here are required to grant permissions to the GITHUB_TOKEN to use the id-token
    permissions:
      id-token: write



    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.DEPLOYMENT_ROLE }}
        role-session-name: OIDCSession
        aws-region: 'us-east-1'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        npm install -g aws-cdk@2.25.0
        cdk --version
    
    - name: Synth stack
      run: cdk synth
      env:
        AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        VPC_ID: ${{ secrets.VPC_ID }}
        AMI_NAME: ${{ secrets.AMI_NAME }}
        ALLOW_PORTS: ${{ secrets.ALLOW_PORTS }}
        GLOBAL_ALLOW_PORTS: ${{ secrets.GLOBAL_ALLOW_PORTS }}
        KEY_NAME: ${{ secrets.KEY_NAME }}
        USER_DATA: ${{ secrets.USER_DATA }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        
